// それぞれの名前にシングルかダブルクォートがあれば調整すること
function initSongs() {
    return [
                {song: '39みゅーじっく! / みきとP feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/DWIQrnssvtg?start=696','https://www.youtube.com/embed/BAOHCnO-61U?start=2196','https://www.youtube.com/embed/wYuPp0_IEzw?start=757',]},
                {song: 'adrenaline!!! / TrySail',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=4644',]},
                {song: 'Ahoy!!我ら宝鐘海賊団☆ / 宝鐘マリン',youtubeLinks: ['https://www.youtube.com/embed/OaoXRdhYww4?start=1358','https://www.youtube.com/embed/ysGivfdP6hc?start=5830','https://www.youtube.com/embed/C91H632s35c?start=3082',]},
                {song: 'AXIA ～ダイスキでダイキライ～ / ワルキューレ / マクロス',youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=1957','https://www.youtube.com/embed/Mf_aQhvlbzw?start=1122','https://www.youtube.com/embed/J_punqVl29E?start=1791',]},
                {song: 'Baby Sweet Berry Love / 小倉唯',youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=1166','https://www.youtube.com/embed/Bb-_gqD7WtI?start=7272','https://www.youtube.com/embed/Hh4JokzhVd4?start=7684',]},
                {song: 'Beat Eater / ポリスピカデリー feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/OaoXRdhYww4?start=2634','https://www.youtube.com/embed/-k6epJzL7q4?start=3609',]},
                {song: 'Berry Sweet Berry Love / 小倉唯',youtubeLinks: ['https://www.youtube.com/embed/PuSp-BzS4n4?start=4652',]},
                {song: 'BON VOYAGE! / Bon-Bon Blanco',youtubeLinks: ['https://www.youtube.com/embed/Z10gH2hUtGo?start=979',]},
                {song: 'Booo! / TOKOTOKO(西沢さんP) feat. 音街ウナ',youtubeLinks: ['https://www.youtube.com/embed/SO_nPZyBNKI?start=4740',]},
                {song: 'Butter-Fly / 和田光司',youtubeLinks: ['https://www.youtube.com/embed/FcurNdxnouo?start=3379',]},
                {song: 'Catch You Catch Me / グミ',youtubeLinks: ['https://www.youtube.com/embed/AS0Q-1eHZYY?start=3013','https://www.youtube.com/embed/8QXDFhckBSw?start=1292','https://www.youtube.com/embed/TZoNtw63LYc?start=1545',]},
                {song: 'Connecting Happy!! / ペコリーヌ(CV:M・A・O)、コッコロ(CV:伊藤美来)、キャル(CV:立花理香)',youtubeLinks: ['https://www.youtube.com/embed/TIqOfp4AlqE?start=1370','https://www.youtube.com/embed/Bb-_gqD7WtI?start=6819','https://www.youtube.com/embed/-cgh9bqo0zc?start=2736',]},
                {song: "Daydream cafe / Petit Rabbit's",youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=423','https://www.youtube.com/embed/yI8oGUjJLTY?start=909','https://www.youtube.com/embed/TZoNtw63LYc?start=4680',]},
                {song: 'daze / じん feat.メイリア from GARNiDELiA',youtubeLinks: ['https://www.youtube.com/embed/Z10gH2hUtGo?start=6308',]},
                {song: "Don't say 'lazy' / 放課後ティータイム",youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=6285',]},
                {song: 'EAT ME / OSTER project feat.GUMI',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=6920','https://www.youtube.com/embed/8QXDFhckBSw?start=5973',]},
                {song: 'Fantastic future / 田村ゆかり',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=2590','https://www.youtube.com/embed/-k6epJzL7q4?start=1193',]},
                {song: 'Girlish Lover / 自らを演出する乙女の会',youtubeLinks: ['https://www.youtube.com/embed/BAOHCnO-61U?start=648','https://www.youtube.com/embed/RthZr86j428?start=6528','https://www.youtube.com/embed/rr_6waP9U90?start=7355',]},
                {song: 'Go Just Go! / デレマス',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=2620',]},
                {song: 'GO!GO!MANIAC / 放課後ティータイム',youtubeLinks: ['https://www.youtube.com/embed/OaoXRdhYww4?start=3499','https://www.youtube.com/embed/XrO7HVCjhWU?start=7997',]},
                {song: 'God knows... / 涼宮ハルヒ',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=5098','https://www.youtube.com/embed/PuSp-BzS4n4?start=2002','https://www.youtube.com/embed/rr_6waP9U90?start=2443',]},
                {song: 'Happy Coming / ティータイム',youtubeLinks: ['https://www.youtube.com/embed/kHSe-wXncWk?start=2949','https://www.youtube.com/embed/CEiVzn391ww?start=6303',]},
                {song: 'Honey♡Come!! / 小倉唯',youtubeLinks: ['https://www.youtube.com/embed/QQinXJgrh3A?start=699','https://www.youtube.com/embed/PuSp-BzS4n4?start=6668','https://www.youtube.com/embed/Hh4JokzhVd4?start=3746',]},
                {song: 'HOT LIMIT / T.M.Revolution',youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=1048','https://www.youtube.com/embed/P8A1wsMzZrY?start=4143','https://www.youtube.com/embed/32BHMgB92mA?start=2950',]},
                {song: 'I・LOVE・YOU!! / 小倉唯',youtubeLinks: ['https://www.youtube.com/embed/-cgh9bqo0zc?start=3662',]},
                {song: 'Jungle P / 5050',youtubeLinks: ['https://www.youtube.com/embed/WO9OnjkdGLg?start=537',]},
                {song: 'KING / Kanaria feat. GUMI',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=6816','https://www.youtube.com/embed/BAOHCnO-61U?start=1534','https://www.youtube.com/embed/C91H632s35c?start=5839',]},
                {song: "Let's Go!スマイルプリキュア / 池田彩",youtubeLinks: ['https://www.youtube.com/embed/sSiwCEBfc8Q?start=4080',]},
                {song: 'look at the sea / おいしくるメロンパン',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=6082','https://www.youtube.com/embed/WO9OnjkdGLg?start=4834','https://www.youtube.com/embed/7vPHOWACitQ?start=7164',]},
                {song: 'Los! Los! Los! / ターニャ・デグレチャフ(悠木碧)',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=2225',]},
                {song: 'Love Ra*bits Party!! / Ra*bits',youtubeLinks: ['https://www.youtube.com/embed/OaoXRdhYww4?start=4942','https://www.youtube.com/embed/-k6epJzL7q4?start=7274',]},
                {song: 'Love So Sweet / 嵐',youtubeLinks: ['https://www.youtube.com/embed/PuSp-BzS4n4?start=1035',]},
                {song: 'LOVEずっきゅん / 相対性理論',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=1311',]},
                {song: 'LUVORATORRRRRY! / ギガP・れをる feat. GUMI, 鏡音リン',youtubeLinks: ['https://www.youtube.com/embed/9pGRLmhrFDs?start=2055','https://www.youtube.com/embed/d1aB8NJ59eY?start=1546',]},
                {song: 'magnet / minato(流星P) feat. 初音ミク, 巡音ルカ',youtubeLinks: ['https://www.youtube.com/embed/d1aB8NJ59eY?start=704',]},
                {song: 'motto☆派手にね！ / 戸松遥',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=626','https://www.youtube.com/embed/ysGivfdP6hc?start=623','https://www.youtube.com/embed/TZoNtw63LYc?start=5140',]},
                {song: 'One Night Carnival / 氣志團',youtubeLinks: ['https://www.youtube.com/embed/wwLayqzGBUk?start=6407','https://www.youtube.com/embed/4MuViBigrAk?start=1272',]},
                {song: 'only my railgun / flipSide',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=4612','https://www.youtube.com/embed/J3aGXDIXmd4?start=428','https://www.youtube.com/embed/_RwuzTtI9Wg?start=5077',]},
                {song: 'Pretender / Official髭男dism',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=5392',]},
                {song: 'PUNCH☆MIND☆HAPPINESS / Happy Clover',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=2004','https://www.youtube.com/embed/P8A1wsMzZrY?start=5108','https://www.youtube.com/embed/1-zUmfrpsZw?start=7322',]},
                {song: 'Q&A リサイタル! / 戸松遥',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=7155','https://www.youtube.com/embed/P8A1wsMzZrY?start=653','https://www.youtube.com/embed/x5KUeugshSc?start=1377',]},
                {song: 'rain stops, good-by / におP feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/Mf_aQhvlbzw?start=593',]},
                {song: 'RESTART POiNTER / IDOLiSH7',youtubeLinks: ['https://www.youtube.com/embed/wYuPp0_IEzw?start=7056',]},
                {song: 'Rising Hope / LiSA',youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=2864','https://www.youtube.com/embed/TIqOfp4AlqE?start=931','https://www.youtube.com/embed/1-zUmfrpsZw?start=2996',]},
                {song: 'RPG / SEKAI NO OWARI',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=2446',]},
                {song: 'secret base ～君がくれたもの～ / ZONE',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=4192','https://www.youtube.com/embed/Mf_aQhvlbzw?start=4377','https://www.youtube.com/embed/wYuPp0_IEzw?start=4836',]},
                {song: 'Share The World / 東方神起',youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=2581','https://www.youtube.com/embed/pn-uHcqsmas?start=4496','https://www.youtube.com/embed/wwLayqzGBUk?start=7621',]},
                {song: "sister's noise / flipSide",youtubeLinks: ['https://www.youtube.com/embed/J_punqVl29E?start=2262',]},
                {song: "Snow halation / μ's",youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=482','https://www.youtube.com/embed/wwLayqzGBUk?start=4763','https://www.youtube.com/embed/_RwuzTtI9Wg?start=5940',]},
                {song: 'sweets parade / 髏々宮カルタ(花澤香菜)',youtubeLinks: ['https://www.youtube.com/embed/AS0Q-1eHZYY?start=1474','https://www.youtube.com/embed/Y3sgrivK_Hg?start=2909','https://www.youtube.com/embed/wYuPp0_IEzw?start=2008',]},
                {song: 'Tell Your World / livetune feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/8QXDFhckBSw?start=845','https://www.youtube.com/embed/ILg4TTmlWrY?start=5989','https://www.youtube.com/embed/PFXLihKPvl0?start=3140',]},
                {song: 'This game / 鈴木このみ',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=892','https://www.youtube.com/embed/DPydyWe23AY?start=4945','https://www.youtube.com/embed/xR8HBW78LNI?start=6882',]},
                {song: 'Together / あきよしふみえ',youtubeLinks: ['https://www.youtube.com/embed/C91H632s35c?start=4428',]},
                {song: 'True My Heart / ave;new feat.佐倉紗織',youtubeLinks: ['https://www.youtube.com/embed/csVWnElzTEw?start=6166',]},
                {song: 'Tulip / 速水奏(CV. 飯田友子)、塩見周子(CV. ルゥティン)、城ヶ崎美嘉(CV. 佳村はるか)、宮本フレデリカ(CV. 高野麻美)、一ノ瀬志希(CV. 藍原ことみ)',youtubeLinks: ['https://www.youtube.com/embed/TIqOfp4AlqE?start=2130',]},
                {song: 'U.S.A. / DA PUMP',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=1035','https://www.youtube.com/embed/cnWAXc6B_sg?start=2883',]},
                {song: 'Viva! Spark!トロピカル～ジュ！ プリキュア / Machico',youtubeLinks: ['https://www.youtube.com/embed/PFXLihKPvl0?start=1687',]},
                {song: 'WiSH VOYAGE /  IDOLiSH7',youtubeLinks: ['https://www.youtube.com/embed/xrb-W6v8fj8?start=960',]},
                {song: 'Wishing / レム(水瀬いのり)',youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=4276','https://www.youtube.com/embed/Mf_aQhvlbzw?start=6918','https://www.youtube.com/embed/VUGNbrgbWwg?start=1897',]},
                {song: 'Yeah!めっちゃホリディ / 松浦亜弥',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=6727','https://www.youtube.com/embed/Z10gH2hUtGo?start=5215','https://www.youtube.com/embed/PFXLihKPvl0?start=4555',]},
                {song: 'YY / ロイ / ドラマ ハコヅメ〜たたかう!交番女子〜',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=2063',]},
                {song: 'Zzz / 佐咲紗花',youtubeLinks: ['https://www.youtube.com/embed/PFXLihKPvl0?start=6418',]},
                {song: "あゝオオサカdream'n night / どついたれ本舗",youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=1561','https://www.youtube.com/embed/ld4EakCzJDo?start=7600','https://www.youtube.com/embed/CG8OzDxY3h8?start=5908',]},
                {song: 'アイデンティティ / Kanaria feat. 初音ミク, GUMI',youtubeLinks: ['https://www.youtube.com/embed/d1aB8NJ59eY?start=1166','https://www.youtube.com/embed/4MuViBigrAk?start=3883','https://www.youtube.com/embed/32BHMgB92mA?start=1790',]},
                {song: 'アイドル / YOASOBI',youtubeLinks: ['https://www.youtube.com/embed/PFXLihKPvl0?start=3505',]},
                {song: 'あいまいクエスチョン / yamada/あいざわ文庫',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=7936',]},
                {song: 'アゲアゲアゲイン / Mitchie M feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/4MuViBigrAk?start=7809','https://www.youtube.com/embed/xrb-W6v8fj8?start=6963',]},
                {song: 'アサガオの散る頃に / じっぷす feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/Z10gH2hUtGo?start=3167',]},
                {song: 'アニマル / DECO*27 feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=747','https://www.youtube.com/embed/Y3sgrivK_Hg?start=6302','https://www.youtube.com/embed/ILg4TTmlWrY?start=959',]},
                {song: 'あの日タイムマシン / LONG SHOT PARTY',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=2318','https://www.youtube.com/embed/b9ILjcCMZJE?start=4882',]},
                {song: 'あわてんぼうのサンタクロース',youtubeLinks: ['https://www.youtube.com/embed/kHSe-wXncWk?start=490',]},
                {song: "い～やい～やい～や / Neru & z'5 feat. 鏡音リン & 鏡音レン",youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=3888','https://www.youtube.com/embed/wqMuM1yqh2I?start=2996',]},
                {song: 'いーあるふぁんくらぶ / みきとP feat. GUMI,鏡音リン',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=5881','https://www.youtube.com/embed/d1aB8NJ59eY?start=2325','https://www.youtube.com/embed/rr_6waP9U90?start=2076',]},
                {song: 'いかないで / 想太 feat. 歌愛ユキ',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=3100',]},
                {song: 'いけないボーダーライン / ワルキューレ / マクロス',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=3464','https://www.youtube.com/embed/CG8OzDxY3h8?start=3473','https://www.youtube.com/embed/CEiVzn391ww?start=1699',]},
                {song: 'いのちの名前 / 木村弓',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=930','https://www.youtube.com/embed/Mf_aQhvlbzw?start=3700','https://www.youtube.com/embed/J_punqVl29E?start=3129',]},
                {song: 'インドア系ならトラックメイカー / Yunomi & nicamoq',youtubeLinks: ['https://www.youtube.com/embed/XrO7HVCjhWU?start=7593',]},
                {song: 'ヴァンパイア / DECO*27 feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/F0tEQGR0rxs?start=3505','https://www.youtube.com/embed/ILg4TTmlWrY?start=1815','https://www.youtube.com/embed/HQW0BpvX9dQ?start=4373',]},
                {song: 'ウィーアー / きただにひろし',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=434','https://www.youtube.com/embed/uHhL80SAUTA?start=4117','https://www.youtube.com/embed/C91H632s35c?start=3998',]},
                {song: 'うまぴょい伝説 / ウマ娘',youtubeLinks: ['https://www.youtube.com/embed/pn-uHcqsmas?start=1480','https://www.youtube.com/embed/XrO7HVCjhWU?start=6565','https://www.youtube.com/embed/wqMuM1yqh2I?start=6541',]},
                {song: 'ウンディーネ / 牧野由依',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=2169','https://www.youtube.com/embed/Mf_aQhvlbzw?start=7522',]},
                {song: 'エヴリデイドリーム / 佐久間まゆ(牧野由依)',youtubeLinks: ['https://www.youtube.com/embed/AS0Q-1eHZYY?start=596',]},
                {song: 'おじゃま虫 / DECO*27 feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=4675','https://www.youtube.com/embed/PreyUMesYZY?start=7099','https://www.youtube.com/embed/wYuPp0_IEzw?start=5313',]},
                {song: 'おジャ魔女カーニバル!! / MAHO堂',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=1819','https://www.youtube.com/embed/PuSp-BzS4n4?start=613','https://www.youtube.com/embed/7vPHOWACitQ?start=4396',]},
                {song: 'おちゃめ機能 / ゴジマジP feat. 重音テト',youtubeLinks: ['https://www.youtube.com/embed/QQinXJgrh3A?start=2395','https://www.youtube.com/embed/QwbgjvRyVWY?start=736','https://www.youtube.com/embed/rr_6waP9U90?start=1672',]},
                {song: 'オツキミリサイタル / じん(自然の敵P) feat. IA',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=1039',]},
                {song: 'オトナブルー / 新しい学校のリーダーズ',youtubeLinks: ['https://www.youtube.com/embed/32BHMgB92mA?start=1490','https://www.youtube.com/embed/7vPHOWACitQ?start=2065',]},
                {song: 'おねがいダーリン / ナナホシ管弦楽団 feat. ONE',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=6065','https://www.youtube.com/embed/9pGRLmhrFDs?start=3752',]},
                {song: 'おねだりShall We～？ / 前川みく(CV高森奈津美)',youtubeLinks: ['https://www.youtube.com/embed/QwbgjvRyVWY?start=3552',]},
                {song: 'おひめさまになりたいのッ！ / OSTER project feat.鏡音リン',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=3732','https://www.youtube.com/embed/sSiwCEBfc8Q?start=3091',]},
                {song: 'オリオンをなぞる /  UNISON SQUARE GARDEN',youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=2841','https://www.youtube.com/embed/PuSp-BzS4n4?start=4174','https://www.youtube.com/embed/Hh4JokzhVd4?start=4090',]},
                {song: 'お願い！シンデレラ / CINDERELLA PROJECT',youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=1959','https://www.youtube.com/embed/AS0Q-1eHZYY?start=3650','https://www.youtube.com/embed/J_punqVl29E?start=1346',]},
                {song: 'お願いダーリン / ナナホシ管弦楽団 feat. ONE',youtubeLinks: ['https://www.youtube.com/embed/QQinXJgrh3A?start=3095','https://www.youtube.com/embed/BAOHCnO-61U?start=4890','https://www.youtube.com/embed/wqMuM1yqh2I?start=5322',]},
                {song: 'ガーネット / 奥華子',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=958','https://www.youtube.com/embed/P8A1wsMzZrY?start=4535','https://www.youtube.com/embed/PFXLihKPvl0?start=692',]},
                {song: 'カオスが極まる / UNISON SQUARE GARDEN',youtubeLinks: ['https://www.youtube.com/embed/J_punqVl29E?start=3878',]},
                {song: 'かくしん的☆めたまるふぉ～ぜっ! / 土間うまる(田中あいみ)',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=1467','https://www.youtube.com/embed/qsXeQ-mY71Y?start=3516','https://www.youtube.com/embed/32BHMgB92mA?start=2093',]},
                {song: 'ガチャガチャきゅ〜と・ふぃぎゅ@メイト / MOSAIC.WAV',youtubeLinks: ['https://www.youtube.com/embed/csVWnElzTEw?start=5684','https://www.youtube.com/embed/rr_6waP9U90?start=6259',]},
                {song: 'カブトムシ / aiko',youtubeLinks: ['https://www.youtube.com/embed/P8A1wsMzZrY?start=1163','https://www.youtube.com/embed/F0tEQGR0rxs?start=2560','https://www.youtube.com/embed/RthZr86j428?start=5598',]},
                {song: 'からくりピエロ (Karakuri Pierrot)',youtubeLinks: ['https://www.youtube.com/embed/Hh4JokzhVd4?start=6209',]},
                {song: 'からくりピエロ / 40mP feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=3369','https://www.youtube.com/embed/mxFulATd6S4?start=6101','https://www.youtube.com/embed/wwLayqzGBUk?start=5498',]},
                {song: 'かわいいだけじゃだめですか？ / CUTIE STREET',youtubeLinks: ['https://www.youtube.com/embed/_RwuzTtI9Wg?start=573',]},
                {song: "きっと青春が聞こえる / μ's",youtubeLinks: ['https://www.youtube.com/embed/P8A1wsMzZrY?start=3202','https://www.youtube.com/embed/CG8OzDxY3h8?start=7794','https://www.youtube.com/embed/rr_6waP9U90?start=5192',]},
                {song: 'キドアイラク / Task feat. 初音ミク, GUMI',youtubeLinks: ['https://www.youtube.com/embed/ysGivfdP6hc?start=7280',]},
                {song: 'ギミー！レボリューション / 内田真礼',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=922','https://www.youtube.com/embed/Bb-_gqD7WtI?start=4217','https://www.youtube.com/embed/xrb-W6v8fj8?start=1831',]},
                {song: 'キミに100パーセント / きゃりーぱみゅぱみゅ',youtubeLinks: ['https://www.youtube.com/embed/csVWnElzTEw?start=3389',]},
                {song: 'キャットラビング / 香椎モイミ feat. 可不',youtubeLinks: ['https://www.youtube.com/embed/QQinXJgrh3A?start=347','https://www.youtube.com/embed/ysGivfdP6hc?start=1073','https://www.youtube.com/embed/xrb-W6v8fj8?start=4672',]},
                {song: 'きゅうくらりん / いよわ',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=932',]},
                {song: 'キリトリセン / 40mP feat. GUMI',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=468','https://www.youtube.com/embed/Bb-_gqD7WtI?start=1147',]},
                {song: 'ゴーストルール / DECO*27 feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=1973','https://www.youtube.com/embed/O6yLVZllncQ?start=5672','https://www.youtube.com/embed/_RwuzTtI9Wg?start=2069',]},
                {song: 'こっち向いてBaby / ryo(supercell) feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=989','https://www.youtube.com/embed/PuSp-BzS4n4?start=7087','https://www.youtube.com/embed/TZoNtw63LYc?start=7832',]},
                {song: 'コトバのうた / 40㍍P feat. 初音ミク ･ GUMI',youtubeLinks: ['https://www.youtube.com/embed/PreyUMesYZY?start=2019',]},
                {song: 'コネクト / ClariS',youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=4848','https://www.youtube.com/embed/F0tEQGR0rxs?start=5858','https://www.youtube.com/embed/_RwuzTtI9Wg?start=3244',]},
                {song: 'さくらんぼ / 大塚愛',youtubeLinks: ['https://www.youtube.com/embed/pn-uHcqsmas?start=4950','https://www.youtube.com/embed/ysGivfdP6hc?start=2659','https://www.youtube.com/embed/TZoNtw63LYc?start=8565',]},
                {song: 'さくらんぼキッス 〜爆発だも〜ん〜 / KOTOKO',youtubeLinks: ['https://www.youtube.com/embed/J_punqVl29E?start=3481','https://www.youtube.com/embed/7vPHOWACitQ?start=6700',]},
                {song: 'シャルル / バルーン feat. v flower',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=5507','https://www.youtube.com/embed/9pGRLmhrFDs?start=6439',]},
                {song: 'シュガーソングとビターステップ / UNISON SQUARE GARDEN',youtubeLinks: ['https://www.youtube.com/embed/OaoXRdhYww4?start=3050','https://www.youtube.com/embed/O6yLVZllncQ?start=2082','https://www.youtube.com/embed/rr_6waP9U90?start=2957',]},
                {song: 'シュガーロス / 和ぬか',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=4506',]},
                {song: 'シル・ヴ・プレジデント / P丸様。',youtubeLinks: ['https://www.youtube.com/embed/QQinXJgrh3A?start=3524','https://www.youtube.com/embed/O6yLVZllncQ?start=9101','https://www.youtube.com/embed/Hh4JokzhVd4?start=1567',]},
                {song: 'ジングルベル',youtubeLinks: ['https://www.youtube.com/embed/kHSe-wXncWk?start=6132',]},
                {song: 'スイートマジック / Junky feat. 鏡音リン',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=6551','https://www.youtube.com/embed/O6yLVZllncQ?start=9851','https://www.youtube.com/embed/TZoNtw63LYc?start=1071',]},
                {song: 'スキスキ絶頂症 / koyori(電ポルP) feat.GUMI',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=2393','https://www.youtube.com/embed/ILg4TTmlWrY?start=7095','https://www.youtube.com/embed/Hh4JokzhVd4?start=5257',]},
                {song: 'ずんだパーリナイ (Zunda Party Night)',youtubeLinks: ['https://www.youtube.com/embed/TZoNtw63LYc?start=6564',]},
                {song: 'セツナトリップ / Last Note. feat.GUMI',youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=3877',]},
                {song: 'ダーリンダンス / かいりきベア feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/DWIQrnssvtg?start=1388','https://www.youtube.com/embed/ysGivfdP6hc?start=8292','https://www.youtube.com/embed/TZoNtw63LYc?start=3173',]},
                {song: 'だいしきゅーだいしゅき / femme fatale',youtubeLinks: ['https://www.youtube.com/embed/OaoXRdhYww4?start=3736','https://www.youtube.com/embed/SO_nPZyBNKI?start=1751',]},
                {song: 'ダダダダ天使 / ナナヲアカリ',youtubeLinks: ['https://www.youtube.com/embed/xR8HBW78LNI?start=6300','https://www.youtube.com/embed/XrO7HVCjhWU?start=2568','https://www.youtube.com/embed/TZoNtw63LYc?start=6177',]},
                {song: 'タッチ / 岩崎良美',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=1840',]},
                {song: 'だんご大家族 / 茶太',youtubeLinks: ['https://www.youtube.com/embed/Mf_aQhvlbzw?start=1587',]},
                {song: 'だんだん早くなる / 40mP feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/SO_nPZyBNKI?start=932',]},
                {song: 'チェチェ・チェック・ワンツー！ / 和田たけあき(くらげP) feat. 結月ゆかり',youtubeLinks: ['https://www.youtube.com/embed/DWIQrnssvtg?start=4928',]},
                {song: 'チェリー / スピッツ',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=1962',]},
                {song: 'チェリボム / Silent Siren',youtubeLinks: ['https://www.youtube.com/embed/AS0Q-1eHZYY?start=2315','https://www.youtube.com/embed/O6yLVZllncQ?start=5242','https://www.youtube.com/embed/Y3sgrivK_Hg?start=1529',]},
                {song: 'チカっとチカ千花っ♡ / 藤原千花(CV. 小原好美)',youtubeLinks: ['https://www.youtube.com/embed/cnWAXc6B_sg?start=2209','https://www.youtube.com/embed/ysGivfdP6hc?start=3114','https://www.youtube.com/embed/1-zUmfrpsZw?start=7082',]},
                {song: 'チャイナアドバイス / 相対性理論',youtubeLinks: ['https://www.youtube.com/embed/QwbgjvRyVWY?start=1595',]},
                {song: 'ちゅ、多様性。 / あの',youtubeLinks: ['https://www.youtube.com/embed/wqMuM1yqh2I?start=2154',]},
                {song: 'てをつなごう / ハムちゃんず',youtubeLinks: ['https://www.youtube.com/embed/wYuPp0_IEzw?start=3587','https://www.youtube.com/embed/rr_6waP9U90?start=7772',]},
                {song: 'とまどい→レシピ / みかくにんぐッ！（照井春佳、松井恵理子、吉田有里）',youtubeLinks: ['https://www.youtube.com/embed/J3aGXDIXmd4?start=1021','https://www.youtube.com/embed/XrO7HVCjhWU?start=6111','https://www.youtube.com/embed/xrb-W6v8fj8?start=3256',]},
                {song: 'ドレミファロンド / 40㍍P feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/DWIQrnssvtg?start=6295','https://www.youtube.com/embed/8QXDFhckBSw?start=5632','https://www.youtube.com/embed/TZoNtw63LYc?start=5649',]},
                {song: 'トンデモワンダーズ / sasakure. UK feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/9pGRLmhrFDs?start=710','https://www.youtube.com/embed/XrO7HVCjhWU?start=4147',]},
                {song: 'ド屑 / なきそ feat. 歌愛ユキ',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=6081',]},
                {song: 'なかよし!〇!なかよし! / チマメ隊',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=635',]},
                {song: 'ニンジーン Loves you yeah! / ランカ・リー / マクロス',youtubeLinks: ['https://www.youtube.com/embed/SO_nPZyBNKI?start=7466','https://www.youtube.com/embed/MvZwm0yEZvE?start=5535',]},
                {song: 'ね～え？ / 松浦亜弥',youtubeLinks: ['https://www.youtube.com/embed/AS0Q-1eHZYY?start=1055','https://www.youtube.com/embed/SO_nPZyBNKI?start=6939','https://www.youtube.com/embed/4MuViBigrAk?start=7314',]},
                {song: 'ネトゲ廃人シュプレヒコール / さつきがてんこもり feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=5559',]},
                {song: 'ハイタッチ☆メモリー / 小倉唯',youtubeLinks: ['https://www.youtube.com/embed/WO9OnjkdGLg?start=4359','https://www.youtube.com/embed/cnWAXc6B_sg?start=7697',]},
                {song: 'はじめてのチュウ / あんしんパパ',youtubeLinks: ['https://www.youtube.com/embed/sSiwCEBfc8Q?start=2589','https://www.youtube.com/embed/Bb-_gqD7WtI?start=5647','https://www.youtube.com/embed/-cgh9bqo0zc?start=5369',]},
                {song: 'パジャマパーティーズのうた (Pajama Parties no Uta)',youtubeLinks: ['https://www.youtube.com/embed/Hh4JokzhVd4?start=6923',]},
                {song: 'はっぴぃ にゅう にゃあ / 芹沢文乃 (CV. 伊藤かな恵), 梅ノ森千世 (CV. 井口裕香), 霧谷希 (CV. 竹達彩奈)',youtubeLinks: ['https://www.youtube.com/embed/MvZwm0yEZvE?start=681','https://www.youtube.com/embed/PFXLihKPvl0?start=4069','https://www.youtube.com/embed/TZoNtw63LYc?start=600',]},
                {song: 'ハッピー・ジャムジャム / しまじろう',youtubeLinks: ['https://www.youtube.com/embed/sSiwCEBfc8Q?start=480','https://www.youtube.com/embed/XrO7HVCjhWU?start=2936','https://www.youtube.com/embed/HQW0BpvX9dQ?start=1351',]},
                {song: 'ハッピーシンセサイザ / EasyPop feat. 巡音ルカ, GUMI',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=4514','https://www.youtube.com/embed/cnWAXc6B_sg?start=442','https://www.youtube.com/embed/d1aB8NJ59eY?start=1967',]},
                {song: 'はなまるぴっぴはよいこだけ / A応P',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=4070',]},
                {song: 'ハム太郎とっとこうた / ハムちゃんず',youtubeLinks: ['https://www.youtube.com/embed/sSiwCEBfc8Q?start=5610','https://www.youtube.com/embed/uHhL80SAUTA?start=5035','https://www.youtube.com/embed/PuSp-BzS4n4?start=7869',]},
                {song: 'バラライカ / 月島きらり starring 久住小春(モーニング娘。)',youtubeLinks: ['https://www.youtube.com/embed/FcurNdxnouo?start=1498','https://www.youtube.com/embed/HQW0BpvX9dQ?start=6690','https://www.youtube.com/embed/C91H632s35c?start=3591',]},
                {song: 'バレンタイン・キッス / 渡り廊下走り隊7',youtubeLinks: ['https://www.youtube.com/embed/SO_nPZyBNKI?start=3454','https://www.youtube.com/embed/BAOHCnO-61U?start=5667','https://www.youtube.com/embed/rr_6waP9U90?start=4049',]},
                {song: 'ハレ晴レユカイ / 涼宮ハルヒの憂鬱',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=2534','https://www.youtube.com/embed/uHhL80SAUTA?start=3759','https://www.youtube.com/embed/x5KUeugshSc?start=4808',]},
                {song: 'ハロ／ハワユ / ナノウ feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=3642',]},
                {song: 'ヒバナ / DECO*27 feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=2905','https://www.youtube.com/embed/CG8OzDxY3h8?start=5452','https://www.youtube.com/embed/xrb-W6v8fj8?start=5059',]},
                {song: 'ビバハピ / Mitchie M feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/ld4EakCzJDo?start=539',]},
                {song: 'ひまわりの約束 / 秦基博',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=8346','https://www.youtube.com/embed/Mf_aQhvlbzw?start=2269','https://www.youtube.com/embed/4MuViBigrAk?start=5823',]},
                {song: 'ファッとして桃源郷 / 新庄かなえ(CV.三森すずこ) (※音量注意)',youtubeLinks: ['https://www.youtube.com/embed/PreyUMesYZY?start=3809',]},
                {song: 'ファンサ / HoneyWorks feat. mona(CV：夏川椎菜)',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=3662','https://www.youtube.com/embed/PreyUMesYZY?start=6656','https://www.youtube.com/embed/_RwuzTtI9Wg?start=6370',]},
                {song: 'フォニイ / ツミキ feat. 可不',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=1663','https://www.youtube.com/embed/ILg4TTmlWrY?start=3506','https://www.youtube.com/embed/C91H632s35c?start=6642',]},
                {song: 'フライングゲット / AKB48',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=2920',]},
                {song: 'フリージア / Uru',youtubeLinks: ['https://www.youtube.com/embed/PreyUMesYZY?start=5320','https://www.youtube.com/embed/VUGNbrgbWwg?start=4456','https://www.youtube.com/embed/C91H632s35c?start=6115',]},
                {song: 'プリキュア5、 フル・スロットルGOGO! / 工藤真由',youtubeLinks: ['https://www.youtube.com/embed/sSiwCEBfc8Q?start=1686',]},
                {song: 'ヘビーローテーション / AKB48',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=526',]},
                {song: 'ぼなぺてぃーと♡S / ブレンド・A',youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=3907','https://www.youtube.com/embed/BAOHCnO-61U?start=8024','https://www.youtube.com/embed/TZoNtw63LYc?start=3670',]},
                {song: 'ホワイトハッピー / MARETU feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=1558',]},
                {song: 'まりんぶるう・らんでぶう / 深海奏汰',youtubeLinks: ['https://www.youtube.com/embed/Z10gH2hUtGo?start=374',]},
                {song: 'みくみくにしてあげる♪ / ika_mo feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/QwbgjvRyVWY?start=4936',]},
                {song: 'ミニモニ。ジャンケンぴょん！ / ミニモニ。',youtubeLinks: ['https://www.youtube.com/embed/QwbgjvRyVWY?start=1199',]},
                {song: 'メイド・イン・トキメキ♪ / Ra*bits',youtubeLinks: ['https://www.youtube.com/embed/uHhL80SAUTA?start=1655','https://www.youtube.com/embed/ILg4TTmlWrY?start=8752','https://www.youtube.com/embed/C91H632s35c?start=7512',]},
                {song: 'めざせポケモンマスター / 松本梨香',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=5478','https://www.youtube.com/embed/FcurNdxnouo?start=4692',]},
                {song: 'メニメニマニマニ / 高宮なすの(鳴海杏子)',youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=3433','https://www.youtube.com/embed/HQW0BpvX9dQ?start=5728','https://www.youtube.com/embed/TZoNtw63LYc?start=6909',]},
                {song: 'メランコリック / Junky feat.鏡音リン',youtubeLinks: ['https://www.youtube.com/embed/DWIQrnssvtg?start=6679','https://www.youtube.com/embed/XrO7HVCjhWU?start=485','https://www.youtube.com/embed/QwbgjvRyVWY?start=4605',]},
                {song: 'メリッサ / ポルノグラフィティ',youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=4633','https://www.youtube.com/embed/cnWAXc6B_sg?start=888',]},
                {song: 'メリュー / n-buna feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=4732','https://www.youtube.com/embed/9pGRLmhrFDs?start=4896',]},
                {song: 'メルティ♡キッチン / Ra*bits',youtubeLinks: ['https://www.youtube.com/embed/HQW0BpvX9dQ?start=7682','https://www.youtube.com/embed/TZoNtw63LYc?start=9015','https://www.youtube.com/embed/wqMuM1yqh2I?start=3837',]},
                {song: 'メルト / ryo(supercell) feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=5173','https://www.youtube.com/embed/9pGRLmhrFDs?start=3306','https://www.youtube.com/embed/O6yLVZllncQ?start=4191',]},
                {song: 'もうそう♡えくすぷれす / 千石撫子/花澤香菜 / アニメ 囮物語',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=5012','https://www.youtube.com/embed/O6yLVZllncQ?start=7790','https://www.youtube.com/embed/TZoNtw63LYc?start=1913',]},
                {song: 'もってけ！セーラーふく / らきすた',youtubeLinks: ['https://www.youtube.com/embed/SO_nPZyBNKI?start=2110',]},
                {song: 'モニタリング / DECO*27 feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/_RwuzTtI9Wg?start=3730',]},
                {song: 'ゆるふわ樹海ガール / 石風呂 feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=2899','https://www.youtube.com/embed/C91H632s35c?start=7017',]},
                {song: 'ようかい体操第一 / Dream5',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=4537',]},
                {song: 'ようこそジャパリパークへ / どうぶつビスケッツ×PPP',youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=1680','https://www.youtube.com/embed/Bb-_gqD7WtI?start=1757','https://www.youtube.com/embed/CEiVzn391ww?start=2545',]},
                {song: "ライオン / May'n/中島愛 / マクロス",youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=2383','https://www.youtube.com/embed/PreyUMesYZY?start=2869','https://www.youtube.com/embed/32BHMgB92mA?start=2520',]},
                {song: 'ラムのラブソング / 松谷祐子',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=2198','https://www.youtube.com/embed/CG8OzDxY3h8?start=6267','https://www.youtube.com/embed/TZoNtw63LYc?start=2412',]},
                {song: 'ルカルカ★ナイトフィーバー / samfree feat. 巡音ルカ',youtubeLinks: ['https://www.youtube.com/embed/QwbgjvRyVWY?start=5125',]},
                {song: 'ルマ / かいりきベア feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=1489','https://www.youtube.com/embed/CG8OzDxY3h8?start=4585','https://www.youtube.com/embed/xrb-W6v8fj8?start=3784',]},
                {song: 'ロキ / みきとP feat. 鏡音リン',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=1420','https://www.youtube.com/embed/b9ILjcCMZJE?start=1620','https://www.youtube.com/embed/_RwuzTtI9Wg?start=2465',]},
                {song: 'ロマンスの神様 / 広瀬香美',youtubeLinks: ['https://www.youtube.com/embed/TIqOfp4AlqE?start=2527',]},
                {song: 'ワールドワイドワンダー / TOKOTOKO(西沢さんP) feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/8QXDFhckBSw?start=1689','https://www.youtube.com/embed/-k6epJzL7q4?start=700','https://www.youtube.com/embed/rr_6waP9U90?start=4396',]},
                {song: 'ワーワーワールド / Giga, Mitchie M feat. 初音ミク, 鏡音リン',youtubeLinks: ['https://www.youtube.com/embed/OaoXRdhYww4?start=982','https://www.youtube.com/embed/HQW0BpvX9dQ?start=642','https://www.youtube.com/embed/Hh4JokzhVd4?start=1984',]},
                {song: '愛してる / 高鈴',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=1388',]},
                {song: '愛のしるし / PUFFY',youtubeLinks: ['https://www.youtube.com/embed/wqMuM1yqh2I?start=672',]},
                {song: '愛言葉Ⅲ (Ai Kotoba Ⅲ)',youtubeLinks: ['https://www.youtube.com/embed/Hh4JokzhVd4?start=5570',]},
                {song: '可愛くてごめん / HoneyWorks feat. ちゅーたん（CV：早見沙織）',youtubeLinks: ['https://www.youtube.com/embed/4MuViBigrAk?start=1765','https://www.youtube.com/embed/J_punqVl29E?start=2770','https://www.youtube.com/embed/7vPHOWACitQ?start=3773',]},
                {song: '可愛くなりたい / HoneyWorks feat.鎖那',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=5629','https://www.youtube.com/embed/SO_nPZyBNKI?start=6436','https://www.youtube.com/embed/HQW0BpvX9dQ?start=1563',]},
                {song: '夏のお嬢さん / 榊原郁恵',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=4943',]},
                {song: '夏祭り / Whiteberry',youtubeLinks: ['https://www.youtube.com/embed/Z10gH2hUtGo?start=4708','https://www.youtube.com/embed/PFXLihKPvl0?start=2131','https://www.youtube.com/embed/rr_6waP9U90?start=752',]},
                {song: '夏待ち (Natsu Machi)',youtubeLinks: ['https://www.youtube.com/embed/CEiVzn391ww?start=1172',]},
                {song: '花に亡霊 / ヨルシカ',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=481','https://www.youtube.com/embed/F0tEQGR0rxs?start=5073','https://www.youtube.com/embed/J_punqVl29E?start=480',]},
                {song: '花ハ踊レヤいろはにほ / チーム“ハナヤマタ”',youtubeLinks: ['https://www.youtube.com/embed/SO_nPZyBNKI?start=1221','https://www.youtube.com/embed/-cgh9bqo0zc?start=6974','https://www.youtube.com/embed/TZoNtw63LYc?start=4282',]},
                {song: '回レ！雪月花 / 歌組雪月花',youtubeLinks: ['https://www.youtube.com/embed/PreyUMesYZY?start=2415','https://www.youtube.com/embed/XrO7HVCjhWU?start=2212',]},
                {song: '快眠！安眠！スヤリスト生活 / スヤリス姫(CV. 水瀬いのり)',youtubeLinks: ['https://www.youtube.com/embed/csVWnElzTEw?start=4582','https://www.youtube.com/embed/5tWggvV1FK8?start=5205',]},
                {song: '海色 / AKINO from bless4',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=4009','https://www.youtube.com/embed/R3AsX31YKNU?start=5453',]},
                {song: '崖の上のポニョ / 藤岡藤巻と大橋のぞみ',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=1402','https://www.youtube.com/embed/xR8HBW78LNI?start=7379','https://www.youtube.com/embed/MvZwm0yEZvE?start=5727',]},
                {song: '丸の内サディスティック / 椎名林檎',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=3311','https://www.youtube.com/embed/F0tEQGR0rxs?start=4270',]},
                {song: '気まぐれロマンティック / いきものがかり',youtubeLinks: ['https://www.youtube.com/embed/PFXLihKPvl0?start=5123','https://www.youtube.com/embed/Hh4JokzhVd4?start=1022',]},
                {song: '空も飛べるはず / スピッツ',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=1501','https://www.youtube.com/embed/PFXLihKPvl0?start=1277',]},
                {song: '君に届け / flumpool',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=3458',]},
                {song: '君の知らない物語 / supercell',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=1931','https://www.youtube.com/embed/Bb-_gqD7WtI?start=2698','https://www.youtube.com/embed/rr_6waP9U90?start=6842',]},
                {song: '君色に染まる / TOKOTOKO(西沢さんP) feat. GUMI',youtubeLinks: ['https://www.youtube.com/embed/DWIQrnssvtg?start=2497',]},
                {song: '喧嘩上等 / 氣志團',youtubeLinks: ['https://www.youtube.com/embed/pn-uHcqsmas?start=595','https://www.youtube.com/embed/wwLayqzGBUk?start=6718',]},
                {song: '言わないけどね。 / 高木さん(高橋李依)',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=6848',]},
                {song: '好き！雪！本気マジック / Mitchie M feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=3022','https://www.youtube.com/embed/b9ILjcCMZJE?start=8712','https://www.youtube.com/embed/xrb-W6v8fj8?start=6626',]},
                {song: '紅蓮華 / LiSA',youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=3705',]},
                {song: '雑草魂なめんなよ！ / Taiki(山崎大輝)',youtubeLinks: ['https://www.youtube.com/embed/xR8HBW78LNI?start=920','https://www.youtube.com/embed/4MuViBigrAk?start=6824','https://www.youtube.com/embed/-cgh9bqo0zc?start=5789',]},
                {song: '残響散歌 / Aimer',youtubeLinks: ['https://www.youtube.com/embed/b9ILjcCMZJE?start=3226',]},
                {song: '残酷な天使のテーゼ / 高橋洋子',youtubeLinks: ['https://www.youtube.com/embed/sSiwCEBfc8Q?start=1254','https://www.youtube.com/embed/VUGNbrgbWwg?start=3317','https://www.youtube.com/embed/C91H632s35c?start=5029',]},
                {song: '私の彼はパイロット / リン・ミンメイ(飯島真理)',youtubeLinks: ['https://www.youtube.com/embed/AS0Q-1eHZYY?start=3430',]},
                {song: '手のひらを太陽に / 宮城まり子 & ビクター児童合唱団',youtubeLinks: ['https://www.youtube.com/embed/RthZr86j428?start=1089',]},
                {song: '呪文降臨 ～マジカル・フォース / Sister MAYO',youtubeLinks: ['https://www.youtube.com/embed/sSiwCEBfc8Q?start=4844',]},
                {song: '粛聖!! ロリ神レクイエム☆ / しぐれうい',youtubeLinks: ['https://www.youtube.com/embed/_RwuzTtI9Wg?start=1097',]},
                {song: '女々しくて / ゴールデンボンバー',youtubeLinks: ['https://www.youtube.com/embed/4MuViBigrAk?start=4273',]},
                {song: '少女レイ / みきとP feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=2131','https://www.youtube.com/embed/VUGNbrgbWwg?start=6951','https://www.youtube.com/embed/C91H632s35c?start=2653',]},
                {song: '少年よ我に帰れ / やくしまるえつこメトロオーケストラ / アニメ 輪るピングドラム',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=2507',]},
                {song: '乗ってけ！ジャパリビート (Notteke! Japari Beat)',youtubeLinks: ['https://www.youtube.com/embed/Hh4JokzhVd4?start=5073',]},
                {song: '侵略ノススメ☆ / イカ娘(金元寿子)',youtubeLinks: ['https://www.youtube.com/embed/OaoXRdhYww4?start=6306',]},
                {song: '寝・逃・げでリセット！ / 柊つかさ(福原香織)',youtubeLinks: ['https://www.youtube.com/embed/pn-uHcqsmas?start=3619','https://www.youtube.com/embed/VUGNbrgbWwg?start=7397','https://www.youtube.com/embed/rr_6waP9U90?start=4759',]},
                {song: '心臓デモクラシー / みきとP feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/Mf_aQhvlbzw?start=6474','https://www.youtube.com/embed/P8A1wsMzZrY?start=6181','https://www.youtube.com/embed/_RwuzTtI9Wg?start=5474',]},
                {song: '森のくまさん (Mori no Kuma-san)',youtubeLinks: ['https://www.youtube.com/embed/Hh4JokzhVd4?start=5891',]},
                {song: '神っぽいな / ピノキオピー feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=2638','https://www.youtube.com/embed/ysGivfdP6hc?start=3590','https://www.youtube.com/embed/CEiVzn391ww?start=2128',]},
                {song: '星間飛行 / ランカ・リー(中島愛) / マクロス',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=2767','https://www.youtube.com/embed/pn-uHcqsmas?start=6609','https://www.youtube.com/embed/wYuPp0_IEzw?start=1234',]},
                {song: '青いベンチ / サスケ',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=3658','https://www.youtube.com/embed/wwLayqzGBUk?start=8015','https://www.youtube.com/embed/7vPHOWACitQ?start=4816',]},
                {song: '青空のラプソディ / fhána',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=518','https://www.youtube.com/embed/PreyUMesYZY?start=5813','https://www.youtube.com/embed/wYuPp0_IEzw?start=3937',]},
                {song: '青春バスガイド / Berryz工房',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=394','https://www.youtube.com/embed/ysGivfdP6hc?start=1831','https://www.youtube.com/embed/-cgh9bqo0zc?start=6203',]},
                {song: '青春ライン / いきものがかり',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=4147','https://www.youtube.com/embed/Z10gH2hUtGo?start=2548',]},
                {song: '赤いスイートピー / 松田聖子',youtubeLinks: ['https://www.youtube.com/embed/4MuViBigrAk?start=802','https://www.youtube.com/embed/MvZwm0yEZvE?start=3061',]},
                {song: '千本桜 / 黒うさP feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=6047','https://www.youtube.com/embed/XrO7HVCjhWU?start=5689',]},
                {song: '全力バタンキュー / A応P',youtubeLinks: ['https://www.youtube.com/embed/pn-uHcqsmas?start=2229',]},
                {song: '創世のアクエリオン / AKINO',youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=4145','https://www.youtube.com/embed/qsXeQ-mY71Y?start=781','https://www.youtube.com/embed/Hh4JokzhVd4?start=4572',]},
                {song: '奏 / スキマスイッチ',youtubeLinks: ['https://www.youtube.com/embed/Gkim8b5GohE?start=5981','https://www.youtube.com/embed/QwbgjvRyVWY?start=2350','https://www.youtube.com/embed/32BHMgB92mA?start=8821',]},
                {song: '太陽曰く燃えよカオス / 後ろから這いより隊G(ニャル子×クー子×珠緒)',youtubeLinks: ['https://www.youtube.com/embed/DWIQrnssvtg?start=5866','https://www.youtube.com/embed/wwLayqzGBUk?start=1459',]},
                {song: '脱法ロック / Neru feat.鏡音レン',youtubeLinks: ['https://www.youtube.com/embed/R3AsX31YKNU?start=6745',]},
                {song: '天ノ弱 / 164 feat. GUMI',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=1042','https://www.youtube.com/embed/ld4EakCzJDo?start=1370','https://www.youtube.com/embed/RthZr86j428?start=7291',]},
                {song: '天使にふれたよ! / 放課後ティータイム / アニメ けいおん!2期挿入歌',youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=3367','https://www.youtube.com/embed/FcurNdxnouo?start=7692','https://www.youtube.com/embed/J_punqVl29E?start=5126',]},
                {song: '点描の唄 / Mrs. GREEN APPLE',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=4267',]},
                {song: '桃色片思い / 松浦亜弥',youtubeLinks: ['https://www.youtube.com/embed/QQinXJgrh3A?start=1915','https://www.youtube.com/embed/O6yLVZllncQ?start=7384','https://www.youtube.com/embed/pn-uHcqsmas?start=4076',]},
                {song: '独りんぼエンヴィー / 電ポル feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/PFXLihKPvl0?start=5651','https://www.youtube.com/embed/DPydyWe23AY?start=4225',]},
                {song: '突撃ラブハート / FIRE BOMBER',youtubeLinks: ['https://www.youtube.com/embed/J3aGXDIXmd4?start=7419',]},
                {song: '虹色・クマクマ / ランカ・リー / マクロス',youtubeLinks: ['https://www.youtube.com/embed/SO_nPZyBNKI?start=5117','https://www.youtube.com/embed/VUGNbrgbWwg?start=437',]},
                {song: '如月アテンション / じん feat. IA',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=3728',]},
                {song: '破滅の純情 / ワルキューレ / マクロス',youtubeLinks: ['https://www.youtube.com/embed/RthZr86j428?start=1426',]},
                {song: '白い雪のプリンセスは / のぼる↑ feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=4873',]},
                {song: '白金ディスコ / 阿良々木月火(井口裕香)',youtubeLinks: ['https://www.youtube.com/embed/QQinXJgrh3A?start=2779','https://www.youtube.com/embed/qsXeQ-mY71Y?start=3115','https://www.youtube.com/embed/Hh4JokzhVd4?start=7319',]},
                {song: '秘密のトワレ / 一ノ瀬志希(CV. 藍原ことみ)',youtubeLinks: ['https://www.youtube.com/embed/P8A1wsMzZrY?start=2139','https://www.youtube.com/embed/CG8OzDxY3h8?start=7342','https://www.youtube.com/embed/wqMuM1yqh2I?start=4705',]},
                {song: '秘密の扉から会いにきて / 田村ゆかり',youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=1477','https://www.youtube.com/embed/O6yLVZllncQ?start=10583','https://www.youtube.com/embed/Hh4JokzhVd4?start=8072',]},
                {song: '美少女無罪♡パイレーツ / 宝鐘マリン',youtubeLinks: ['https://www.youtube.com/embed/_RwuzTtI9Wg?start=2863',]},
                {song: '秒針を噛む / ずっと真夜中でいいのに。',youtubeLinks: ['https://www.youtube.com/embed/PuSp-BzS4n4?start=1533',]},
                {song: '不確定性☆COSMIC MOVEMENT / ワルキューレ / マクロス',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=4206','https://www.youtube.com/embed/P8A1wsMzZrY?start=1705','https://www.youtube.com/embed/TZoNtw63LYc?start=2707',]},
                {song: '風になる / つじあやの',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=2631','https://www.youtube.com/embed/F0tEQGR0rxs?start=7273','https://www.youtube.com/embed/Hh4JokzhVd4?start=2764',]},
                {song: '変わらないもの / 奥華子',youtubeLinks: ['https://www.youtube.com/embed/F0tEQGR0rxs?start=1047','https://www.youtube.com/embed/PFXLihKPvl0?start=6795',]},
                {song: '夢をかなえてドラえもん / mao',youtubeLinks: ['https://www.youtube.com/embed/TIqOfp4AlqE?start=4649','https://www.youtube.com/embed/J_punqVl29E?start=4542','https://www.youtube.com/embed/Hh4JokzhVd4?start=3255',]},
                {song: '無限ダラダラガンダーラ / なみぐる feat. 琴葉 茜・葵',youtubeLinks: ['https://www.youtube.com/embed/_RwuzTtI9Wg?start=4739',]},
                {song: '妄想感傷代償連盟 / DECO*27 feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=3519','https://www.youtube.com/embed/J_punqVl29E?start=937',]},
                {song: '夜に駆ける / YOASOBI',youtubeLinks: ['https://www.youtube.com/embed/ysGivfdP6hc?start=3941','https://www.youtube.com/embed/ILg4TTmlWrY?start=8234',]},
                {song: '夜もすがら君想ふ / 西沢さんP feat. GUMI',youtubeLinks: ['https://www.youtube.com/embed/2vYNd5EXGNI?start=557','https://www.youtube.com/embed/8QXDFhckBSw?start=7472','https://www.youtube.com/embed/_RwuzTtI9Wg?start=1598',]},
                {song: '夜咄ディセイブ / じん(自然の敵P) feat. IA',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=3023','https://www.youtube.com/embed/9pGRLmhrFDs?start=2486','https://www.youtube.com/embed/wwLayqzGBUk?start=2776',]},
                {song: '夕景イエスタデイ / じん feat. IA',youtubeLinks: ['https://www.youtube.com/embed/H-XMoyLIdKQ?start=1025','https://www.youtube.com/embed/cnWAXc6B_sg?start=7332','https://www.youtube.com/embed/Hh4JokzhVd4?start=6593',]},
                {song: '夕立のりぼん / みきとP feat. MAYU',youtubeLinks: ['https://www.youtube.com/embed/mDQ-NfchOII?start=6394','https://www.youtube.com/embed/wwLayqzGBUk?start=1040','https://www.youtube.com/embed/TZoNtw63LYc?start=7407',]},
                {song: '旅立ちの日に / 合唱',youtubeLinks: ['https://www.youtube.com/embed/DOjZ578wkCY?start=1533',]},
                {song: '恋 / 星野源',youtubeLinks: ['https://www.youtube.com/embed/QQinXJgrh3A?start=1281','https://www.youtube.com/embed/uHhL80SAUTA?start=2546','https://www.youtube.com/embed/rr_6waP9U90?start=1183',]},
                {song: '恋のヒメヒメぺったんこ / 姫野湖鳥(CV:田村ゆかり)',youtubeLinks: ['https://www.youtube.com/embed/ysGivfdP6hc?start=6291',]},
                {song: '恋はきっと急上昇☆ ~Rock Buster~ / のぼる↑ feat. GUMI',youtubeLinks: ['https://www.youtube.com/embed/PreyUMesYZY?start=903','https://www.youtube.com/embed/BAOHCnO-61U?start=5291','https://www.youtube.com/embed/-cgh9bqo0zc?start=2236',]},
                {song: '恋は混沌の隷也 / 後ろから這いより隊G(ニャル子,クー子,珠緒)',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=3085','https://www.youtube.com/embed/PreyUMesYZY?start=3405','https://www.youtube.com/embed/wqMuM1yqh2I?start=3443',]},
                {song: '恋愛サーキュレーション / 千石撫子(花澤香菜)',youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=4391','https://www.youtube.com/embed/F0tEQGR0rxs?start=8124','https://www.youtube.com/embed/J_punqVl29E?start=6283',]},
                {song: '恋愛フィロソフィア / 黒うさP feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=5236','https://www.youtube.com/embed/9pGRLmhrFDs?start=4085','https://www.youtube.com/embed/5tWggvV1FK8?start=5548',]},
                {song: '恋愛裁判 / 40mP feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=5423','https://www.youtube.com/embed/wwLayqzGBUk?start=4023','https://www.youtube.com/embed/_RwuzTtI9Wg?start=4204',]},
                {song: '恋空予報 / 電ポルP feat.GUMI',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=5127','https://www.youtube.com/embed/jpiOqVkVPhg?start=3110','https://www.youtube.com/embed/QwbgjvRyVWY?start=5578',]},
                {song: '六兆年と一夜物語 / kemu feat.IA',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=1797','https://www.youtube.com/embed/b9ILjcCMZJE?start=2500',]},
                {song: '檄!帝国華撃団 / 真宮寺さくら(横山智佐)&帝国歌劇団',youtubeLinks: ['https://www.youtube.com/embed/pn-uHcqsmas?start=1844','https://www.youtube.com/embed/sYimIV2nqaI?start=5851','https://www.youtube.com/embed/7vPHOWACitQ?start=6219',]},
                {song: '翡翠のまち / メル feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=4091','https://www.youtube.com/embed/uHhL80SAUTA?start=7800','https://www.youtube.com/embed/TZoNtw63LYc?start=8230',]},
                {song: '恋は混沌の隷也 / 後ろから這いより隊G(ニャル子,クー子,珠緒)',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=3085','https://www.youtube.com/embed/PreyUMesYZY?start=3405','https://www.youtube.com/embed/wqMuM1yqh2I?start=3443',]},
                {song: '恋愛サーキュレーション / 千石撫子(花澤香菜)',youtubeLinks: ['https://www.youtube.com/embed/3vws756U5hk?start=4391','https://www.youtube.com/embed/F0tEQGR0rxs?start=8124','https://www.youtube.com/embed/J_punqVl29E?start=6283',]},
                {song: '恋愛フィロソフィア / 黒うさP feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/mxFulATd6S4?start=5236','https://www.youtube.com/embed/9pGRLmhrFDs?start=4085','https://www.youtube.com/embed/5tWggvV1FK8?start=5548',]},
                {song: '恋愛裁判 / 40mP feat.初音ミク',youtubeLinks: ['https://www.youtube.com/embed/OERjf_NyIUA?start=5423','https://www.youtube.com/embed/wwLayqzGBUk?start=4023','https://www.youtube.com/embed/_RwuzTtI9Wg?start=4204',]},
                {song: '恋空予報 / 電ポルP feat.GUMI',youtubeLinks: ['https://www.youtube.com/embed/bhrTPDBx61k?start=5127','https://www.youtube.com/embed/jpiOqVkVPhg?start=3110','https://www.youtube.com/embed/QwbgjvRyVWY?start=5578',]},
                {song: '六兆年と一夜物語 / kemu feat.IA',youtubeLinks: ['https://www.youtube.com/embed/DPydyWe23AY?start=1797','https://www.youtube.com/embed/b9ILjcCMZJE?start=2500',]},
                {song: '檄!帝国華撃団 / 真宮寺さくら(横山智佐)&帝国歌劇団',youtubeLinks: ['https://www.youtube.com/embed/pn-uHcqsmas?start=1844','https://www.youtube.com/embed/sYimIV2nqaI?start=5851','https://www.youtube.com/embed/7vPHOWACitQ?start=6219',]},
                {song: '翡翠のまち / メル feat. 初音ミク',youtubeLinks: ['https://www.youtube.com/embed/jpiOqVkVPhg?start=4091','https://www.youtube.com/embed/uHhL80SAUTA?start=7800','https://www.youtube.com/embed/TZoNtw63LYc?start=8230',]},
    ];
}
